### ISSUE TITLE
Limit Leaderboard "Pokale" to 3 

### ISSUE THREAD

**Issue by robonder** [sopra-fs23-group-20/client#100]

**Comment by L-Huber** [comment]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/71383238/234257177-91499a04-f06e-471f-9932-1a1cb67955fe.png">

**Comment by JSha91** [comment]
This should be working now! --> Louis tested it, and now it only shows three trophies in the leaderBoard (same as in the scoreBoard).
