### ISSUE TITLE
Leaderboard and Scoreboard should be mobile compatible

### ISSUE THREAD

**Issue by dariomonopoli-dev** [sopra-fs23-group-20/client#132]

**Comment by L-Huber** [comment]
maybe use this:
[https://stackoverflow.com/a/60811141](https://stackoverflow.com/a/60811141)

**Comment by L-Huber** [comment]
<img width="386" alt="Bildschirmfoto 2023-05-18 um 11 34 29" src="https://github.com/sopra-fs23-group-20/client/assets/71383238/ffacdd24-87db-4c27-bfff-ea56270c0936">
