### ISSUE TITLE
Final scoreboard displayed, showing total points for each player

### ISSUE THREAD

**Issue by dariomonopoli-dev** [sopra-fs23-group-20/client#32]

**Comment by JSha91** [comment]
- https://github.com/sopra-fs23-group-20/client/commit/982ae2d10fefbfc9f6c6f6b6872a8a45443874a4
- https://github.com/sopra-fs23-group-20/client/commit/cc7921d6996b83783a216c54953ece5171d3d0f6
- https://github.com/sopra-fs23-group-20/client/commit/cc7921d6996b83783a216c54953ece5171d3d0f6
- https://github.com/sopra-fs23-group-20/client/commit/40076b4accec8be268f4657e20a4d796e23a9ddc
- https://github.com/sopra-fs23-group-20/server/commit/f935425382cb2e8a4fa9bd8b4fb79c184cee4573
- https://github.com/sopra-fs23-group-20/server/commit/b0c16ae7f1c51363b07adbbe038dd72dd1850179
