### ISSUE TITLE
At the scoreboard show how many points each player has gained during the last round

### ISSUE THREAD

**Issue by robonder** [sopra-fs23-group-20/client#95]

**Comment by JSha91** [comment]
In my opinion this ticket is useless. Currently you have to wait after each submit until the round is over (independently whether you guessed it correctly or not). Afterwards you will be directed to ScoreBoard where you already see the rankings and the total round Points. I do not see any value to add the points which each player has gained during the last round. Especially under the circumstance that the scoreboard is displayed only for a few seconds before the next round starts.

**Comment by JSha91** [comment]
https://github.com/sopra-fs23-group-20/client/commit/7f5123f09d9190eccdbcfe5c95df1037bebf2121
--> However, we decided to implement this feature finally.
